os:
  - osx
language: node_js
node_js:
  - stable
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn run build-css
  - yarn test:coverage
after_script:
  - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_KEY yarn run coveralls
before_deploy:
  - yarn global add netlify-cli
  - NODE_ENV=production yarn run build
deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./build
  skip_cleanup: true
  on:
    branch: master